### ISSUE TITLE
Error on Meld website

### ISSUE THREAD

**Issue by HerrPi** [meld/meld.github.com#2]
This is probably a thing for the meld mailing list but I'll report it here nevertheless. On http://meldmerge.org/help/keyboard-shortcuts.html both keyboard shortcuts for "Go to the next difference" and "Go to the previous difference" are listed as "Alt + Up". The first one surely has to be "Alt + Down".

**Comment by kaiw** [comment]
I'm sorry for missing this! This repository hasn't really been monitored in the best.

On the upside, this has been fixed.
