### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by KitchM** [meld/meld.github.com#3]
Thanks for the extremely useful program.

I have a few questions:
#1 I am seeing a lot of arrows in the display of Meld.  They do not seem to be addresses in any documentation I have found so far.  Here is one example:
bin---->usr/bin

Is this indicating some sort of symlink?

#2 During the copy process, is it just copying everything from one place to another as in a mirror copy?

#3 Is Meld a decent method to backup one drive to another?

Thanks again.

**Comment by kaiw** [comment]
1. Yes, that's the indication for a symlink
2. I don't know what you mean by a "mirror copy". Meld copies whatever you select to the other folder, and tries to maintain permissions, etc. where possible.
3. I wouldn't recommend using it that way, no. I would suggest using more specialised software for backing up drives, and then if you want to double-check the backup, then you could use Meld for that purpose.

Meld's actual bug tracker is at https://gitlab.gnome.org/GNOME/meld/
